#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libunistring
Version  : 0.9.6
Release  : 6
URL      : http://ftp.gnu.org/gnu/libunistring/libunistring-0.9.6.tar.xz
Source0  : http://ftp.gnu.org/gnu/libunistring/libunistring-0.9.6.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-3.0 LGPL-3.0
Requires: libunistring-lib
Requires: libunistring-doc

%description
GNU LIBUNISTRING - Unicode string library
This library provides functions for manipulating Unicode strings and
for manipulating C strings according to the Unicode standard.

%package dev
Summary: dev components for the libunistring package.
Group: Development
Requires: libunistring-lib

%description dev
dev components for the libunistring package.


%package doc
Summary: doc components for the libunistring package.
Group: Documentation

%description doc
doc components for the libunistring package.


%package lib
Summary: lib components for the libunistring package.
Group: Libraries

%description lib
lib components for the libunistring package.


%prep
%setup -q -n libunistring-0.9.6

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/unistring/cdefs.h
/usr/include/unistring/iconveh.h
/usr/include/unistring/inline.h
/usr/include/unistring/localcharset.h
/usr/include/unistring/stdbool.h
/usr/include/unistring/stdint.h
/usr/include/unistring/version.h
/usr/include/unistring/woe32dll.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libunistring/*
%doc /usr/share/info/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
